org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true


## Mod Properties
modId=gravelnofall
modName=Gravel No Fall
modLicense=BSD 2-Clause License
modGroupId=io.github.makaseloli.gravelnofall
modAuthors=makaseloli
modDescription=Very simple mod that only prevents gravel from falling and makes pickaxes effective for gravel.
modDisplayUrl=https://github.com/makaseloli/Gravel-No-Fall
modIssueTrackerUrl=https://github.com/makaseloli/Gravel-No-Fall/issues
modCredits=


## Fabric Mod Properties
modFabricEnvironment=*
modFabricEntrypoint=io.github.makaseloli.gravelnofall.ModMain
modFabricClientEntrypoint=io.github.makaseloli.gravelnofall.client.ModClient
